/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/client/NewPointRelaisScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/client/StatutPointRelaisScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/client/UploadDocumentsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/client/PointRelaisApprovalScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/client/ChatScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../theme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/client/NewPointRelaisScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/client/StatutPointRelaisScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/client/UploadDocumentsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/client/PointRelaisApprovalScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/client/ChatScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../theme`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../screens/client/NewPointRelaisScreen${`?${string}` | `#${string}` | ''}` | `/../screens/client/StatutPointRelaisScreen${`?${string}` | `#${string}` | ''}` | `/../screens/client/UploadDocumentsScreen${`?${string}` | `#${string}` | ''}` | `/../screens/client/PointRelaisApprovalScreen${`?${string}` | `#${string}` | ''}` | `/../screens/client/ChatScreen${`?${string}` | `#${string}` | ''}` | `/../theme${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/client/NewPointRelaisScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/client/StatutPointRelaisScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/client/UploadDocumentsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/client/PointRelaisApprovalScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/client/ChatScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../theme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
