/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/LanguageContext`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/Traductions`; params?: Router.UnknownInputParams; } | { pathname: `/../test/Test_traduction`; params?: Router.UnknownInputParams; } | { pathname: `/../test/ThemeTestScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/ThemeContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/LanguageContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/Traductions`; params?: Router.UnknownOutputParams; } | { pathname: `/../test/Test_traduction`; params?: Router.UnknownOutputParams; } | { pathname: `/../test/ThemeTestScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../contexts/ThemeContext${`?${string}` | `#${string}` | ''}` | `/../contexts/LanguageContext${`?${string}` | `#${string}` | ''}` | `/../contexts/Traductions${`?${string}` | `#${string}` | ''}` | `/../test/Test_traduction${`?${string}` | `#${string}` | ''}` | `/../test/ThemeTestScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/LanguageContext`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/Traductions`; params?: Router.UnknownInputParams; } | { pathname: `/../test/Test_traduction`; params?: Router.UnknownInputParams; } | { pathname: `/../test/ThemeTestScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
